### ISSUE TITLE
Genstarter hele tiden

### ISSUE THREAD

**Issue by Math6921** [Ramlov/Sky-Universe#1]
Halløj, jeg ville ind og lege med filerne.. men når jeg har lavet base.lua om samt server.cfg.
og starter startserver.bat så bliver den bare ved med at renstarte serveren hele tiden? har rettet port osv?

**Comment by TobiasVester05** [comment]
Jeg har samme problem som Math6921, og af den grund akan jeg ikke joine serveren. Hvad gør jeg?

**Comment by Ramlov** [comment]
Jeg har lige downloadet filerne på en frisk, og gjort **nøjagtigt** hvad der står i installations guiden. Det fungerede fint.
I må have lavet en fejl under opsætningen.
